# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v2
         
         name: Set Up python
       - uses: actions/setup-python@v2.1.3
         with:
           python version: 3.7
      # install python package
       - name: install dependencies
         run: pip install -e '.[dev]'
       
       - name: install pre-commit
         run: pre-commit install
       
       - name: run pre-commit
         run: pre-commit run --all-files
       
       - name: run pytest
         run: pytest
         continue-on-error: false

